# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: from-scratch-pipeline
  path.config: "/usr/share/logstash/pipeline/from-scratch.conf"

- pipeline.id: incremental-pipeline
  path.config: "/usr/share/logstash/pipeline/incremental.conf"

- pipeline.id: sales-order-detail-pipeline
  path.config: "/usr/share/logstash/pipeline/sales_order_detail.conf"

- pipeline.id: employees-pipeline
  path.config: "/usr/share/logstash/pipeline/employees.conf"

- pipeline.id: loans-pipeline
  path.config: "/usr/share/logstash/pipeline/loans.conf"

- pipeline.id: world-pipeline
  path.config: "/usr/share/logstash/pipeline/world.conf"